### ISSUE TITLE
[CONTENT]: Add section for firmware release notes in the firmware tab

### ISSUE THREAD

**Issue by la-firestone** [RobolinkInc/doc-v3#148]
## Context
Louann requested a way to know what changed from one firmware to another. We should host some release notes on our docs site

## Solution

- [x] Create a section for release notes in the firmware section similar in format to our other changelogs. You can fill it with some filler information until you get the real notes from Arnold.

### CoDrone EDU Drone Version 24.9.1

- **New Feature: Motor Stall Prevention** – If the drone detects a problem with one of the motors (like it’s stuck or acting strangely) during takeoff, it will automatically stop trying to fly.

- **Bug Fix: Takeoff improvement** – The firmware has been improved to reduce the frequency of an error with the height sensor during takeoff.

- **Bug Fix: Flight Count Issue Resolved** – Previously, resetting the drone’s settings would also reset the flight time. This has been corrected so your flight time remains accurate.

### CoDrone EDU Controller Version 24.9.1

 - **New Feature: Motor Stall Prevention** – The controller will display "MOTOR STALL" when the drone detects a problem with one or more motors.

- **Bug Fix: Takeoff improvement** –  If the error with the height sensor occurs during a takeoff attempt, the controller will automatically display a “[RANGE GROUND] WRONG VALUE” message.

- **New Feature: Color Sensor Notification During Flight** – When flying, the color sensor status screen will now display a message that it is disabled during flight.

- **Improvement: Display Stability** – The screen will now go blank less often thanks to a speed improvement in how the drone communicates with the display.

- **Improvement: New Screens Added** – We’ve updated the interface to include new screens to match CoDrone EDU (JROTC ed.)

## Test
Go to docs site and click on the "Firmware" tab and see the release notes.

**Comment by dbautista2000** [comment]
Added official release notes
