### ISSUE TITLE
[CONTENT]: Remove "Open in Python" button for features are not yet available in PFR

### ISSUE THREAD

**Issue by la-firestone** [RobolinkInc/doc-v3#151]
## Context 
There are certain features that are not yet available for PFR, so the examples will not work if they try to run it.

## Solution
Remove the button for the following examples:

- [x] new_color_data()
- [x] append_color_data()
- [x] load_classifier()
- [x] predict_colors()
- [x] controller_create_canvas() [Can you also test these? I think it only works with a GUI]
- [x] controller_draw_canvas() [Can you also test these? I think it only works with a GUI]
- [x] controller_preview_canvas() [Can you also test these? I think it only works with a GUI]

**Comment by green-study** [comment]
UI updated, I will test 3 functions next week.

**Comment by green-study** [comment]
It is currently under python library update. 
So it cannot be tested in python-staging. 
I will test it later.

**Comment by la-firestone** [comment]
The PR is ready.
